/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  '/database': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.database.id'];
          created_at?: parameters['rowFilter.database.created_at'];
          name?: parameters['rowFilter.database.name'];
          quote?: parameters['rowFilter.database.quote'];
          avatar?: parameters['rowFilter.database.avatar'];
          instagram?: parameters['rowFilter.database.instagram'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          'Range'?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          'Prefer'?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['database'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** database */
          database?: definitions['database'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.database.id'];
          created_at?: parameters['rowFilter.database.created_at'];
          name?: parameters['rowFilter.database.name'];
          quote?: parameters['rowFilter.database.quote'];
          avatar?: parameters['rowFilter.database.avatar'];
          instagram?: parameters['rowFilter.database.instagram'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.database.id'];
          created_at?: parameters['rowFilter.database.created_at'];
          name?: parameters['rowFilter.database.name'];
          quote?: parameters['rowFilter.database.quote'];
          avatar?: parameters['rowFilter.database.avatar'];
          instagram?: parameters['rowFilter.database.instagram'];
        };
        body: {
          /** database */
          database?: definitions['database'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  '/database-slowmode': {
    get: {
      parameters: {
        query: {
          ipAddress?: parameters['rowFilter.database-slowmode.ipAddress'];
          until?: parameters['rowFilter.database-slowmode.until'];
          /** Filtering Columns */
          select?: parameters['select'];
          /** Ordering */
          order?: parameters['order'];
          /** Limiting and Pagination */
          offset?: parameters['offset'];
          /** Limiting and Pagination */
          limit?: parameters['limit'];
        };
        header: {
          /** Limiting and Pagination */
          'Range'?: parameters['range'];
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit'];
          /** Preference */
          'Prefer'?: parameters['preferCount'];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions['database-slowmode'][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** database-slowmode */
          'database-slowmode'?: definitions['database-slowmode'];
        };
        query: {
          /** Filtering Columns */
          select?: parameters['select'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          ipAddress?: parameters['rowFilter.database-slowmode.ipAddress'];
          until?: parameters['rowFilter.database-slowmode.until'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          ipAddress?: parameters['rowFilter.database-slowmode.ipAddress'];
          until?: parameters['rowFilter.database-slowmode.until'];
        };
        body: {
          /** database-slowmode */
          'database-slowmode'?: definitions['database-slowmode'];
        };
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn'];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  'database': {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
    /** Format: text */
    quote?: string;
    /** Format: text */
    avatar: string;
    /** Format: text */
    instagram?: string;
  };
  'database-slowmode': {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    ipAddress: string;
    /** Format: timestamp with time zone */
    until: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  'preferParams': 'params=single-object';
  /**
   * @description Preference
   * @enum {string}
   */
  'preferReturn': 'return=representation' | 'return=minimal' | 'return=none';
  /**
   * @description Preference
   * @enum {string}
   */
  'preferCount': 'count=none';
  /** @description Filtering Columns */
  'select': string;
  /** @description On Conflict */
  'on_conflict': string;
  /** @description Ordering */
  'order': string;
  /** @description Limiting and Pagination */
  'range': string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  'rangeUnit': string;
  /** @description Limiting and Pagination */
  'offset': string;
  /** @description Limiting and Pagination */
  'limit': string;
  /** @description database */
  'body.database': definitions['database'];
  /** Format: bigint */
  'rowFilter.database.id': string;
  /** Format: timestamp with time zone */
  'rowFilter.database.created_at': string;
  /** Format: text */
  'rowFilter.database.name': string;
  /** Format: text */
  'rowFilter.database.quote': string;
  /** Format: text */
  'rowFilter.database.avatar': string;
  /** Format: text */
  'rowFilter.database.instagram': string;
  /** @description database-slowmode */
  'body.database-slowmode': definitions['database-slowmode'];
  /** Format: text */
  'rowFilter.database-slowmode.ipAddress': string;
  /** Format: timestamp with time zone */
  'rowFilter.database-slowmode.until': string;
}

export interface operations {}

export interface external {}
