name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            .nuxt # nuxt types
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Install Dependencies
        run: yarn
      
      - name: Generate Nuxt types
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn nuxi prepare
      
      - name: Run ESLint
        run: yarn lint
